"""Write PJSIP endpoint blocks for new extensions and reload Asterisk."""
import asyncio
import logging
import os
from ..config import settings

log = logging.getLogger(__name__)

_CONF_HEADER = "; Auto-generated by Dymphna VoIP backend — do not edit manually\n\n"


def _extension_block(number: str, password: str, display_name: str) -> str:
    # A real endpoint that inherits the WebRTC [ext-defaults] template.
    # (Previously marked `(!)` which made it a template and never instantiated.)
    return (
        f"[{number}](ext-defaults)\n"
        f"auth={number}-auth\n"
        f"aors={number}\n"
        f"callerid={display_name} <{number}>\n\n"
        f"[{number}-auth]\n"
        f"type=auth\n"
        f"auth_type=userpass\n"
        f"username={number}\n"
        f"password={password}\n\n"
        f"[{number}]\n"
        f"type=aor\n"
        f"max_contacts=5\n"
        f"qualify_frequency=30\n\n"
    )


async def provision_extension(number: str, password: str, display_name: str) -> None:
    """Append a PJSIP endpoint block for the extension and reload PJSIP."""
    path = settings.pjsip_extensions_path

    try:
        # Read existing content or start fresh
        if os.path.exists(path):
            with open(path, 'r') as f:
                content = f.read()
        else:
            content = _CONF_HEADER

        # Skip if already provisioned
        if f"[{number}-auth]" in content:
            log.info("Extension %s already in pjsip_extensions.conf", number)
            return

        content += _extension_block(number, password, display_name)

        with open(path, 'w') as f:
            f.write(content)

        log.info("Provisioned extension %s in %s", number, path)

        # Reload PJSIP via AMI
        from . import asterisk as ami
        mgr = await ami.get_manager()
        await mgr.send_action({'Action': 'ModuleReload', 'Module': 'res_pjsip.so'})
        log.info("PJSIP reloaded for extension %s", number)

    except Exception as exc:
        log.error("Failed to provision extension %s: %s", number, exc)


async def deprovision_extension(number: str) -> None:
    """Remove a PJSIP endpoint block for the extension and reload PJSIP."""
    path = settings.pjsip_extensions_path
    if not os.path.exists(path):
        return

    try:
        with open(path, 'r') as f:
            lines = f.readlines()

        # Remove all lines belonging to this extension's three blocks
        prefixes = (f"[{number}]", f"[{number}-auth]", f"[{number}](!,ext-defaults)")
        in_block = False
        out_lines = []
        for line in lines:
            stripped = line.strip()
            if any(stripped.startswith(p) for p in (f"[{number}]", f"[{number}-auth]")):
                in_block = True
            if in_block and stripped == '' and out_lines and out_lines[-1].strip() == '':
                in_block = False
                continue
            if not in_block:
                out_lines.append(line)

        with open(path, 'w') as f:
            f.writelines(out_lines)

        from . import asterisk as ami
        mgr = await ami.get_manager()
        await mgr.send_action({'Action': 'ModuleReload', 'Module': 'res_pjsip.so'})
        log.info("Deprovisioned extension %s", number)

    except Exception as exc:
        log.error("Failed to deprovision extension %s: %s", number, exc)
